import type { Locale } from "./i18n/config";

const labels = {
  ja: {
    // Sidebar / nav
    dashboard: "ダッシュボード",
    events: "イベント",
    contacts: "お問い合わせ",
    content: "コンテンツ",
    donations: "寄付",
    products: "商品",
    orders: "注文",
    social: "ソーシャル",
    analytics: "分析",
    redirects: "リダイレクト",
    users: "ユーザー",
    settings: "設定",
    signOut: "ログアウト",

    // Dashboard
    welcome: "ようこそ",
    newMessages: "新着メッセージ",
    contentPosts: "コンテンツ投稿",
    donationsCompleted: "寄付（完了）",
    ordersPending: "注文（保留中）",
    socialDrafts: "ソーシャル下書き",

    // Common
    viewSite: "サイトを見る",
    edit: "編集",
    view: "表示",
    delete: "削除",
    save: "保存",
    cancel: "キャンセル",
    title: "タイトル",
    date: "日付",
    status: "ステータス",
    actions: "操作",
    noData: "データがありません",

    // Events
    newEvent: "新規イベント",
    mode: "形式",
    registrations: "登録",
    noEvents: "イベントはまだありません。",

    // Content
    newPost: "新規投稿",
    type: "種類",
    author: "著者",
    updated: "更新日",
    noContent: "コンテンツはまだありません。",

    // Products
    newProduct: "新規商品",
    variants: "バリエーション",
    priceRange: "価格帯",
    totalStock: "総在庫",
    active: "有効",
    inactive: "無効",
    noProducts: "商品はまだありません。",

    // Orders
    totalOrders: "注文合計",
    awaitingFulfillment: "発送待ち",
    shipped: "発送済み",
    revenue: "売上",
    email: "メール",
    items: "商品",
    total: "合計",
    all: "すべて",
    noOrders: "注文が見つかりません。",
    orderInfo: "注文情報",
    orderItems: "商品一覧",
    shippingName: "配送先名",
    shippingAddress: "配送先住所",
    notes: "メモ",
    product: "商品",
    variant: "バリエーション",
    price: "価格",
    qty: "数量",
    subtotal: "小計",

    // Donations
    totalDonations: "寄付合計",
    completed: "完了",
    activeRecurring: "定期寄付（有効）",
    totalAmount: "合計金額",
    donor: "寄付者",
    amount: "金額",
    donationType: "種類",
    monthly: "月額",
    oneTime: "一回",
    message: "メッセージ",
    noDonations: "寄付が見つかりません。",

    // Contacts
    contactMessages: "お問い合わせメッセージ",
    noContacts: "お問い合わせはまだありません。",

    // Social
    socialPublishing: "ソーシャル投稿",
    composePost: "投稿を作成",
    connectedAccounts: "接続済みアカウント",
    accountConnected: "アカウントが接続されました。",
    connectionFailed: "接続に失敗しました",
    caption: "キャプション",
    account: "アカウント",
    scheduled: "予定",
    published: "公開済み",
    noSocialPosts: "ソーシャル投稿はまだありません。",

    // Analytics
    analyticsAudit: "分析と監査",
    pageViews30d: "ページビュー（30日）",
    totalEvents30d: "イベント合計（30日）",
    eventTypes: "イベント種類",
    eventsByType: "種類別イベント",
    topPages: "人気ページ",
    noEventsRecorded: "まだイベントが記録されていません。",
    noPageViews: "まだページビューが記録されていません。",
    recentAuditLog: "最近の監査ログ",
    time: "時刻",
    user: "ユーザー",
    action: "操作",
    entity: "エンティティ",
    id: "ID",
    noAuditLogs: "監査ログはまだありません。",

    // Redirects
    from: "元パス",
    to: "先パス",
    statusCode: "ステータスコード",
    noRedirects: "リダイレクトはまだ設定されていません。",

    // Users
    addUser: "ユーザー追加",
    name: "名前",
    role: "ロール",
    login: "ログイン",
    created: "作成日",
    password: "パスワード",
    googleOnly: "Google のみ",
  },
  en: {
    dashboard: "Dashboard",
    events: "Events",
    contacts: "Contacts",
    content: "Content",
    donations: "Donations",
    products: "Products",
    orders: "Orders",
    social: "Social",
    analytics: "Analytics",
    redirects: "Redirects",
    users: "Users",
    settings: "Settings",
    signOut: "Sign Out",

    welcome: "Welcome",
    newMessages: "New Messages",
    contentPosts: "Content Posts",
    donationsCompleted: "Donations (Completed)",
    ordersPending: "Orders (Pending)",
    socialDrafts: "Social Drafts",

    viewSite: "View Site",
    edit: "Edit",
    view: "View",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    title: "Title",
    date: "Date",
    status: "Status",
    actions: "Actions",
    noData: "No data",

    newEvent: "New Event",
    mode: "Mode",
    registrations: "Registrations",
    noEvents: "No events yet.",

    newPost: "New Post",
    type: "Type",
    author: "Author",
    updated: "Updated",
    noContent: "No content posts yet.",

    newProduct: "New Product",
    variants: "Variants",
    priceRange: "Price Range",
    totalStock: "Total Stock",
    active: "Active",
    inactive: "Inactive",
    noProducts: "No products yet.",

    totalOrders: "Total Orders",
    awaitingFulfillment: "Awaiting Fulfillment",
    shipped: "Shipped",
    revenue: "Revenue",
    email: "Email",
    items: "Items",
    total: "Total",
    all: "All",
    noOrders: "No orders found.",
    orderInfo: "Order Info",
    orderItems: "Items",
    shippingName: "Shipping Name",
    shippingAddress: "Shipping Address",
    notes: "Notes",
    product: "Product",
    variant: "Variant",
    price: "Price",
    qty: "Qty",
    subtotal: "Subtotal",

    totalDonations: "Total Donations",
    completed: "Completed",
    activeRecurring: "Active Recurring",
    totalAmount: "Total Amount",
    donor: "Donor",
    amount: "Amount",
    donationType: "Type",
    monthly: "Monthly",
    oneTime: "One-time",
    message: "Message",
    noDonations: "No donations found.",

    contactMessages: "Contact Messages",
    noContacts: "No contact messages yet.",

    socialPublishing: "Social Publishing",
    composePost: "Compose Post",
    connectedAccounts: "Connected Accounts",
    accountConnected: "Social account connected successfully.",
    connectionFailed: "Connection failed",
    caption: "Caption",
    account: "Account",
    scheduled: "Scheduled",
    published: "Published",
    noSocialPosts: "No social posts yet.",

    analyticsAudit: "Analytics & Audit",
    pageViews30d: "Page Views (30d)",
    totalEvents30d: "Total Events (30d)",
    eventTypes: "Event Types",
    eventsByType: "Events by Type",
    topPages: "Top Pages",
    noEventsRecorded: "No events recorded yet.",
    noPageViews: "No page views recorded yet.",
    recentAuditLog: "Recent Audit Log",
    time: "Time",
    user: "User",
    action: "Action",
    entity: "Entity",
    id: "ID",
    noAuditLogs: "No audit log entries yet.",

    from: "From",
    to: "To",
    statusCode: "Status",
    noRedirects: "No redirects configured.",

    addUser: "Add User",
    name: "Name",
    role: "Role",
    login: "Login",
    created: "Created",
    password: "Password",
    googleOnly: "Google only",
  },
} as const;

export type AdminLabels = { [K in keyof (typeof labels)["en"]]: string };

export function getLabels(locale: Locale): AdminLabels {
  return labels[locale];
}
